SetParentDoc がcloneを返すようにした
go-generalize/volcago pull request #50
Opened 2022-04-22 04:25 UTC by mopeneko

Closes #49

2022-04-22 04:28 UTC, moezakura requested changes

2022-04-22 04:28 UTC, moezakura commented on generator/templates/gen.go.tmpl
> +	return &repo
新しくインスタンスを作り直さないと、cloneにはならないです。
同じポインタを操作してるので…

2022-04-22 04:32 UTC, moezakura commented on generator/templates/gen.go.tmpl
> +	return &repo
あ、実態を操作してた
これでよさそう

2022-04-22 04:32 UTC, moezakura approved these changes
LGTM

2022-04-22 04:40 UTC, 54m reviewed
新しく関数生やす対応にして欲しいですー

2022-04-22 04:40 UTC, 54m commented on generator/templates/gen.go.tmpl
> +func (repo {{ .RepositoryStructName }}) SetParentDoc(doc *firestore.DocumentRef) {{ .RepositoryInterfaceName }} {
引数名がなくてエラーにならないですかね？
(arg1 Hoge, Hoge)
ってなってるように見える

2022-04-22 04:52 UTC, mopeneko commented on generator/templates/gen.go.tmpl
> +func (repo {{ .RepositoryStructName }}) SetParentDoc(doc *firestore.DocumentRef) {{ .RepositoryInterfaceName }} {
あ、これ返り値です

2022-04-22 04:53 UTC, 54m commented on generator/templates/gen.go.tmpl
> +func (repo {{ .RepositoryStructName }}) SetParentDoc(doc *firestore.DocumentRef) {{ .RepositoryInterfaceName }} {
ほんとや

2022-04-22 05:01 UTC, 54m reviewed
テストコードの追加もお願いします！

2022-04-22 05:17 UTC, mopeneko commented
追加してみたけど、not_autoの実行方法がわからん...

2022-04-22 05:19 UTC, mopeneko commented
make test TEST_OPT='-tags="emulator"' これか

2022-04-22 05:55 UTC, mopeneko commented
え、なんでこれnot foundになるんだ...?

2022-04-22 06:02 UTC, mopeneko commented
今まであったほうのIDがSingle、今追加したやつがFirestoreの自動生成IDになってるっぽい

2022-04-22 06:03 UTC, mopeneko commented
これもうautoで実装したほうが楽なのでは

2022-04-22 06:32 UTC, 54m commented on generator/testfiles/auto/task.go
> +	Sub        *firestore.DocumentRef `firestore:"sub"`
今回の対応でDocumentRefを追加しないと行けなくなる...?

2022-04-22 06:34 UTC, mopeneko commented on generator/testfiles/auto/task.go
> +	Sub        *firestore.DocumentRef `firestore:"sub"`
ならないな
削除

2022-05-06 02:03 UTC, 54m commented on generator/templates/gen.go.tmpl
> +	SetParentDocWithNewInstance(doc *firestore.DocumentRef) {{ .RepositoryInterfaceName }}
メソッド名にずっと違和感を感じていて、NewRepositoryByParentとかどうだろうか

2022-06-01 03:08 UTC, mopeneko commented on generator/templates/gen.go.tmpl
> +	SetParentDocWithNewInstance(doc *firestore.DocumentRef) {{ .RepositoryInterfaceName }}
https://github.com/go-generalize/volcago/pull/50/commits/f682d539dd7a88f8e5c1de95eba0b4321d7d01e1 で修正

2022-06-01 03:44 UTC, mopeneko commented
なんかうちの環境で `go generate` が通らなくなった。。。

2022-06-02 15:20 UTC, 54m commented
> なんかうちの環境で `go generate` が通らなくなった。。。

最新のmaster取り込んでmake gen_samplesした？make buildが一緒に走るから直ると思う！

2022-06-24 07:04 UTC, 54m commented
@mopeneko 
NewRepositoryByParentを利用したテストお願いね

2022-06-26 18:35 UTC, 54m approved these changes
![LGTM](https://image.lgtmoon.dev/165684)

2022-06-26 18:35 UTC, merged